# Docker compose file for rsyslog
# Maintained by somsakc@hotmail.com

version: "3"

services:
  rsyslog:
    image: mbixtech/rsyslog:${TAG}
    hostname: rsyslog
    environment:
      - RSYSLOG_ROTATE_FILES=5
      - RSYSLOG_ROTATE_SIZE=1k
      - TZ=${TZ}
    ports:
      - "5514:5514"
      - "5514:5514/udp"
    volumes:
#      - ${ROOTPATH}/rsyslog.d:/etc/rsyslog.d
#      - ${ROOTPATH}/logrotate.d:/etc/logrotate.d
      - ${ROOTPATH}/log:/var/log
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  setup_rsyslog:
    image: ubuntu:22.04
    user: root
    command: ['/bin/sh', '-c', 'chown -R 1000.1000 /mnt']
    volumes:
      - ${ROOTPATH}:/mnt
